name = "Doku_Autocomplete"
uuid = "06ca0970-9112-4b79-81fb-c1d3ffced68e"
authors = ["Adam Burdett <burdettadam@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
Combinatorics = "1.0"
ProgressMeter = "1.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
